services:
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    working_dir: /app
    ports:
      - "5444:5432"

volumes:
  pgdata:
