services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64
    container_name: ts-mapped-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ts-mapped-redis
    ports:
      - "6380:6379"

  mailpit:
    image: axllent/mailpit
    container_name: ts-mapped-mailpit
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    volumes:
      - mailpit_data:/data

volumes:
  pgdata:
  mailpit_data:
